all:
	g++ -c Node.cpp
	g++ -c AdjacencyList.cpp
	g++ -c LinkedList.cpp
	g++ -c ListNode.cpp
	g++ -c GraphNode.cpp
	g++ -c main.cpp
	g++ Node.o AdjacencyList.o LinkedList.o ListNode.o GraphNode.o main.o -o output
	
removeObjects:
	del *.o